name: Fetch Lyrics

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # dotnet SDK built-in

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - run: dotnet publish /p:Configuration=Release /p:PublishProfile=FolderProfile

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: bin/Release/net6.0/publish/win-x64
          retention-days: 1

  Fetch_Lyrics:
    runs-on: windows-latest # dotnet SDK built-in
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: lyrics

      - name: Checkout submodules to latest
        run: git submodule update --init --recursive && git submodule update --recursive --remote

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Execute Lyrics.exe
        shell: cmd
        run: 'call Lyrics.exe'

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: lyrics
          file_pattern: 'Lyrics/ Lyrics.json'
          commit_message: 'Github Action: Fetch Lyrics'
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run
