name: Fetch Lyrics

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      retry_failed_lyrics:
        description: 'retry_failed_lyrics'
        type: boolean
        required: false
        default: false
      max_count:
        description: 'max_count'
        type: string
        required: false
        default: '2000'
      lyrics:
        description: 'lyrics'
        type: string
        required: false
        default: ''
  repository_dispatch:
    types: [fetch_lyrics]

jobs:
  build:
    runs-on: windows-latest # dotnet SDK built-in

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - run: dotnet publish /p:Configuration=Release /p:PublishProfile=FolderProfile

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: bin/Release/net6.0/publish/win-x64
          retention-days: 7

  Fetch_Lyrics:
    runs-on: windows-latest # dotnet SDK built-in
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: lyrics

      - name: Checkout submodules to latest
        run: git submodule update --init --recursive && git submodule update --recursive --remote

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Checkout appsettings.json from HEAD
        run: 'git checkout HEAD appsettings.json'

      - name: Execute Lyrics.exe (workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: cmd
        env:
          RETRY_FAILED_LYRICS: ${{ github.event.inputs.retry_failed_lyrics }}
          MAX_COUNT: ${{ github.event.inputs.max_count }}
          LYRICS: ${{ github.event.inputs.lyrics }}
        run: 'call Lyrics.exe'

      - name: Execute Lyrics.exe (repository_dispatch)
        if: ${{ github.event_name == 'repository_dispatch' }}
        shell: cmd
        env:
          RETRY_FAILED_LYRICS: ${{ github.event.client_payload.retry_failed_lyrics }}
          MAX_COUNT: ${{ github.event.client_payload.max_count }}
          LYRICS: ${{ github.event.client_payload.lyrics }}
        run: 'call Lyrics.exe'

      - name: Execute Lyrics.exe (schedule, push)
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        shell: cmd
        run: 'call Lyrics.exe'

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: lyrics
          file_pattern: Lyrics Lyrics.json
          skip_checkout: true
          commit_message: 'Github Action: Fetch Lyrics'
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run
